/*******************************************************
 * 
 * Karan Goel, 2013
 * karan@goel.im
 * 
 * TODO: Write this comment!
 * 
 *******************************************************/

package im.goel.MoodicPlayer;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

import utils.Moods;


public class MoodicPlayer implements ActionListener, PropertyChangeListener {

	private static final String key = ""; // Add your API key here
	private static final String secret = ""; // Add your secret here
	private String token; // Token generated by last.fm API
	private static String sessionKey; // must remain static throughout the program run
	private boolean isAuthenticated; // true if user has authenticated already

	public static void main(String[] args) throws IOException {
		new MoodicPlayer();
	}

	private List<TrackInfo> allTracks; // Stores all tracks found for all moods
	private List<String> mbids; // Stores mbids found for all moods
	private Moods moodObj = new Moods();

	private MoodicPlayer() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}

		javax.swing.SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				try {
					isAuthenticated = isAuth();
				} catch (IOException e) {
					e.printStackTrace();
				}
				// Create and show GUI
				initializeFrame();
				initializeMenu();
				initializeNorth();
				frame.add(north, BorderLayout.CENTER);
				frame.setVisible(true);
			}
		});
	}

	/**
	 * @return true if user has already authenticated.
	 */
	private boolean isAuth() throws IOException {
		File file = new File("user.properties");
		if (file.exists()) {
			BufferedReader br = new BufferedReader(new FileReader(file));
			String sessionKey = br.readLine();
			return sessionKey.length() == 36; // TODO: may need to change
		}
		return false;
	}

	/**
	 * Keeps track of events on GUI elements.
	 */
	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == go) {
			// Main button is pressed
			progress.setIndeterminate(true);
			go.setEnabled(false); // disable button
			Task task = new Task();
			task.addPropertyChangeListener(this);
			task.execute(); // start the magic!
		} else if (e.getSource() == step1) {
			// Step 1 of authentication. Send user to auth URL
			try {
				token = getToken();
				//System.out.println(token);
				String authURL = "http://www.last.fm/api/auth/?api_key=" + key + "&token=" + token;
				java.awt.Desktop browser = java.awt.Desktop.getDesktop();
				java.net.URI uri = new java.net.URI(authURL);
				browser.browse(uri);
				step1.setEnabled(false); // Done for step 1
				step2.setEnabled(true); // Enable step 2
			} catch (IOException e1) {
				e1.printStackTrace();
			} catch (JDOMException e1) {
				e1.printStackTrace();
			} catch (URISyntaxException e1) {
				e1.printStackTrace();
			}
		} else if (e.getSource() == step2) {
			// Step 2 of authentication. Generate the sessionKey
			try {
				String sessionKey = getSessionKey(token);
				// Save session key as it is infinite timed
				File file = new File("user.properties");
				BufferedWriter writer = new BufferedWriter(new FileWriter(file));
				writer.write(sessionKey);
				writer.flush();
				writer.close();
			} catch (NoSuchAlgorithmException e1) {
				e1.printStackTrace();
			} catch (IOException e1) {
				e1.printStackTrace();
			}
			String message = "Thank you for authentication. Select your mood\nand click " + 
					"\"Build\" to build your playlist";
			JOptionPane.showMessageDialog(null, message, "Authentication Successful", 
					JOptionPane.INFORMATION_MESSAGE);
			go.setEnabled(true);
		} else if (e.getSource() == about) {
			String message = "Moodic Player is a free and open source playlist builder\n" + 
					"for last.fm. Simply add your account, select your mood and voilà!\n" + 
					"a new playlist will be ready for you in seconds!\n\n" + 
					"Now give beats to your moods!\n\n" + 
					"Open source project by Karan Goel (http://www.goel.im).\n" + 
					"Source code at http://github.com/thekarangoel/MoodicPlayer/";
			JOptionPane.showMessageDialog(null, message, "About Moodic Player", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	/**
	 * Keeps track of the progress to notify the progress bar
	 * to change its value appropriately.
	 */
	public void propertyChange(PropertyChangeEvent e) {
		if ("progress" == e.getPropertyName()) {
			int p = (Integer) e.getNewValue();
			progress.setIndeterminate(false); // Because we know how much change we need
			progress.setValue(p * (100 / mbids.size()) + (100 % mbids.size()));
		}
	}

	/**
	 * Returns the token generated for this session.
	 * @return token generated by this session by last.fm
	 */
	public String getToken() throws IOException, JDOMException {
		String urlToParse = "http://ws.audioscrobbler.com/2.0/?method=auth.gettoken&" + 
				"api_key=" + key + "&api_sig=" + secret;
		try {
			List<Element> list = getList(urlToParse, "auth.gettoken");
			for (int i = 0; i < list.size(); i++) {
				Element node = (Element) list.get(i);
				return node.getText();
			}
		} catch (MalformedURLException e1) {
			e1.printStackTrace();
		} catch (IOException e1) {
			e1.printStackTrace();
		} catch (JDOMException e1) {
			e1.printStackTrace();
		}
		return null;
	}

	/**
	 * Returns the session key as per the last.fm documentation
	 * @param token
	 * @return session key as per the documentation
	 * @throws NoSuchAlgorithmException
	 */
	public String getSessionKey(String token) throws NoSuchAlgorithmException {
		MessageDigest md = MessageDigest.getInstance("MD5");
		String apiSig = "api_key" + key + "methodauth.getSessiontoken" + token + secret;		
		md.update(apiSig.getBytes());
		byte byteData[] = md.digest();
		//convert the byte to hex format
		StringBuffer sb = new StringBuffer();
		for (int i = 0; i < byteData.length; i++) {
			sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
		}		
		String urlToParse = "http://ws.audioscrobbler.com/2.0/?method=auth.getSession&" + 
				"api_key=" + key + "&api_sig=" + sb.toString() + "&token=" + token;
		try {
			List<Element> list = getList(urlToParse, "auth.getSession");
			for (int i = 0; i < list.size(); i++) {
				Element node = (Element) list.get(i);
				return node.getChildText("key");
			}
		} catch (MalformedURLException e1) {
			e1.printStackTrace();
		} catch (IOException e1) {
			e1.printStackTrace();
		} catch (JDOMException e1) {
			e1.printStackTrace();
		}
		return null;
	}

	/**
	 * Required for JDOM. Returns a list of Element's to be parser
	 * found in the given URL.
	 */
	private List<Element> getList(String urlToParse, String method) throws IOException, JDOMException {
		SAXBuilder builder = new SAXBuilder();
		URL website = new URL(urlToParse);
		ReadableByteChannel rbc = Channels.newChannel(website.openStream());
		@SuppressWarnings("resource")
		FileOutputStream fos = new FileOutputStream("request.xml");
		fos.getChannel().transferFrom(rbc, 0, 1 << 24);

		File xmlFile = new File("request.xml");

		Document document = (Document) builder.build(xmlFile);
		Element rootNode = document.getRootElement();

		if (method.equals("tag.gettoptracks")) {
			return rootNode.getChildren("toptracks");
		} else if (method.equals("track.getInfo")) {
			return rootNode.getChildren("track");
		} else if (method.equals("auth.gettoken")) {
			return rootNode.getChildren("token");
		} else if (method.equals("auth.getSession")) {
			return rootNode.getChildren("session");
		} else {
			return null;
		}
	}

	//********************** BUILD GUI **********************//
	private JFrame frame;
	private JPanel north;
	private JProgressBar progress;
	private JComboBox<String> moodSelector;
	private JButton go;
	private JMenuBar menubar;
	private JMenu lastfm;
	private JMenuItem step1, step2, about;

	/**
	 * Initializes the main frame and sets its properties.
	 */
	private void initializeFrame() {
		frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(new Dimension(350, 110));
		frame.setLocation(new Point(400, 300));
		frame.setTitle("Moodic Player");
		frame.setResizable(false);
		frame.setLayout(new BorderLayout());
	}

	/**
	 * Initializes the north panel and sets its properties.
	 */
	private void initializeNorth() {
		north = new JPanel(new GridLayout(1, 3));
		moodSelector = new JComboBox<String>(moodObj.getMoods());
		go = new JButton("Build");
		go.addActionListener(this);
		if (!isAuthenticated) {
			go.setEnabled(false);
		}
		progress = new JProgressBar(0, 100);
		progress.setValue(0);
		north.add(moodSelector);
		north.add(go);
		north.add(progress);
		north.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
	}

	private void initializeMenu() {
		menubar = new JMenuBar();
		lastfm = new JMenu("last.fm Account");
		if (isAuthenticated) {
			lastfm.setEnabled(false);
		}
		menubar.add(lastfm);
		step1 = new JMenuItem("1. Allow Access");
		step1.addActionListener(this);
		lastfm.add(step1);
		step2 = new JMenuItem("2. Proceed");
		step2.addActionListener(this);
		step2.setEnabled(false);
		lastfm.add(step2);
		about = new JMenuItem("About");
		about.addActionListener(this);
		menubar.add(lastfm);
		menubar.add(about);
		frame.setJMenuBar(menubar);
	}
	//********************** BUILD GUI **********************//


	/**
	 * This class is meant to process all things in a background
	 * thread.
	 * @author Karan Goel
	 */
	public class Task extends SwingWorker<Void, Object> {

		private static final String LIMIT = "5"; // number of tracks per tag to find

		@Override
		/**
		 * Everything in this method is done in a separate thread
		 * and not EDT!
		 */
		protected Void doInBackground() {
			//System.out.println(javax.swing.SwingUtilities.isEventDispatchThread());
			String mood = moodSelector.getSelectedItem().toString().toLowerCase();
			List<String> subMoods = moodObj.getSubMoods(mood);

			mbids = getAllMbids(subMoods); // Find all mbids for given moods
			int currentProgress = 0;
			int maxProgress = mbids.size(); // Important so we don't loop unnecessarily
			setProgress(1);

			allTracks = new ArrayList<TrackInfo>();
			while (currentProgress < maxProgress) {
				// Make progress.
				// Run this once for ever mbid
				getTrackInfoForMbid(mbids.get(currentProgress));
				currentProgress = allTracks.size();
				setProgress(Math.min(currentProgress, maxProgress));
			}
			return null;
		}

		/**
		 * This method runs in EDT after background thread is completed.
		 */
		public void done() {
			//System.out.println(javax.swing.SwingUtilities.isEventDispatchThread());
			go.setEnabled(true);
			System.out.println(allTracks.toString());
		}

		/**
		 * Returns a list of string of mbids for upto LIMIT tracks for each
		 * tag (submood)
		 * @param subMoods - a list of moods
		 * @return list of string of mbids for upto LIMIT tracks for each
		 * tag (submood)
		 */
		private List<String> getAllMbids(List<String> subMoods) {
			// START building list of MBID
			List<String> allMbids = new ArrayList<String>();
			for (String tag : subMoods) {
				String urlToParse = "http://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks&" +
						"tag=" + tag + "&api_key=" + key + "&limit=" + LIMIT;
				try {
					List<Element> list = getList(urlToParse, "tag.gettoptracks");
					for (int i = 0; i < list.size(); i++) {
						Element node = (Element) list.get(i);
						List<Element> subList = node.getChildren("track");
						for (int j = 0; j < subList.size(); j++) {
							Element subNode = (Element) subList.get(j);
							String extractedMbid = subNode.getChildText("mbid");
							if (extractedMbid.length() == 36) { // Length of mbid
								allMbids.add(extractedMbid);
							}
						}
					}
				} catch (MalformedURLException e1) {
					e1.printStackTrace();
				} catch (IOException e1) {
					e1.printStackTrace();
				} catch (JDOMException e1) {
					e1.printStackTrace();
				}
			}
			// END building list of MBID
			return allMbids;
		}

		/**
		 * For a given mbid, find the required information, and store
		 * it as a TrackInfo object in the list.
		 * @param mbid of track to find information
		 */
		private void getTrackInfoForMbid(String mbid) {
			// START building list of Info
			String urlToParse = "http://ws.audioscrobbler.com/2.0/?method=track.getInfo&" + 
					"api_key=" + key + "&mbid=" + mbid;
			try {
				List<Element> trackList = getList(urlToParse, "track.getInfo");
				for (int i = 0; i < trackList.size(); i++) {
					Element node = (Element) trackList.get(i);
					String name = node.getChildText("name");
					int playCount = Integer.parseInt(node.getChildText("playcount"));
					int listeners = Integer.parseInt(node.getChildText("listeners"));
					List<Element> artistList = node.getChildren("artist");
					for (int j = 0; j < artistList.size(); j++) {
						Element artistElement = (Element) artistList.get(j);
						allTracks.add(new TrackInfo(name, artistElement.getChildText("name"), 
								mbid, playCount, listeners));
					}
				}
			} catch (MalformedURLException e1) {
				e1.printStackTrace();
			} catch (IOException e1) {
				e1.printStackTrace();
			} catch (JDOMException e1) {
				e1.printStackTrace();
			}
			// END building list of Info
		}

	}

}